# Generated by Django 6.0.6 on 2026-06-09 17:04

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', validators=[tickets.models.validate_poster_file]),
        ),
    ]
